name: Metrics
on:
  schedule: [{cron: "0 * * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@v3.34
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: reumer06
          template: classic
          base: header, activity, community, repositories
          config_display: large
          config_timezone: Asia/Mumbai
          plugin_achievements: no
          plugin_skyline: no
          plugin_isocalendar: yes
          plugin_lines: no
          # plugin_lines_sections: repositories, history
          # plugin_lines_repositories_limit: 2
          # plugin_lines_history_limit: 1
